map $http_x_request_id $real_request_id {
    default $http_x_request_id;
    ""      $request_id;
}

map $http_x_request_from $real_request_from {
    default $http_x_request_from;
    ""      "nginx";
}

log_format access_json_logs escape=json '{"application": "app_name", "component": "nginx", "datetime": "$time_iso8601", "message": "$request", "level": "INFO","channel": "request", "context": {}, "extra": {"request_id": "$real_request_id", "request_from": "$real_request_from"},"metrics": {"id": "$real_request_id", "status": "$status", "duration": $request_time, "size": $body_bytes_sent}}';

server {
    access_log  /dev/stdout access_json_logs;
    error_log   /dev/stdout;
}
