[www]

access.format = "{\"application\": \"app_name\", \"component\": \"php-fpm\", \"datetime\": \"%{%Y-%m-%dT%H:%M:%S%z}t\", \"message\": \"%m %r\", \"level\": \"INFO\", \"channel\": \"request\", \"context\": {}, \"extra\": {}, \"metrics\": {\"status\": \"%s\", \"duration\": %{seconds}d, \"memory\": %M, \"cpu\": %C}}"